blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/forest6511/gdl/discussions
    about: Please ask and answer questions here
  - name: Security Issues
    url: https://github.com/forest6511/gdl/security/policy
    about: Please report security vulnerabilities here