blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/forest6511/godl/discussions
    about: Please ask and answer questions here
  - name: Security Issues
    url: https://github.com/forest6511/godl/security/policy
    about: Please report security vulnerabilities here